import type { NextPage } from 'next'
import Header from '../components/header'
import Head from 'next/head'
import Footer from '../components/footer'
import Projects from '../components/projects'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Portfolio: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&family=Roboto:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.1.0/modern-normalize.min.css" />
      </Head>
      <Header />
      <main>
        <Projects />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Portfolio